In [8]:
import pandas as pd

df = pd.read_csv("clients_data.csv")
df.head()

,Customer_ID,Age,Gender,Item_Purchased,Category,Purchase_Amount_USD,Location,Size,Color,Season,Review_Rating,Subscription_Status,Payment_Method,Shipping_Type,Discount_Applied,Promo_Code_Used,Previous_Purchases,Preferred_Payment_Method,Frequency_of_Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Credit Card,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Bank Transfer,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Cash,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,PayPal,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Cash,Free Shipping,Yes,Yes,31,PayPal,Annually

In [9]:
features = df[['Age', 'Purchase_Amount_USD', 'Previous_Purchases']]

In [10]:
print(df[['Age', 'Purchase_Amount_USD', 'Previous_Purchases']].head())
print(df[['Age', 'Purchase_Amount_USD', 'Previous_Purchases']].shape)

   Age  Purchase_Amount_USD  Previous_Purchases
0   55                   53                  14
1   19                   64                   2
2   50                   73                  23
3   21                   90                  49
4   45                   49                  31
(3900, 3)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)

In [12]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(scaled_data)

In [14]:
df.groupby('Cluster').mean(numeric_only=True)

,Customer_ID,Age,Purchase_Amount_USD,Review_Rating,Previous_Purchases
Cluster,,,,,
0,1926.399865,59.698917,58.569012,3.735792,28.451962
1,2001.076625,36.332817,59.765480,3.748994,11.018576
2,1924.194690,32.469027,61.326549,3.769558,37.684071